export const EMAILJS_CONFIG = {
  SERVICE_ID: 'YOUR_EMAILJS_SERVICE_ID',
  TEMPLATE_ID: 'YOUR_EMAILJS_TEMPLATE_ID',
  PUBLIC_KEY: 'YOUR_EMAILJS_PUBLIC_KEY',
  CONTACT_TEMPLATE_ID: 'YOUR_EMAILJS_CONTACT_TEMPLATE_ID',
}; 